package golang_structs_parser

type AutoGenerated struct {
	Colors struct {
		SuccessGreen   string `json:"--success-green,omitempty"`
		MainColor      string `json:"--main-color,omitempty"`
		MainColorLight string `json:"--main-color-light,omitempty"`
		SecondaryColor string `json:"--secondary-color,omitempty"`
		ErrorRed       string `json:"--error-red,omitempty"`
	} `json:"colors,omitempty"`
	InitialForm struct {
		Comments struct {
			CommentsForm struct {
				GeneralComments string `json:"generalComments,omitempty"`
			} `json:"commentsForm,omitempty"`
		} `json:"comments,omitempty"`
		General struct {
			Client struct {
				Email         string `json:"email,omitempty"`
				FullName      string `json:"fullName,omitempty"`
				CompanyType   string `json:"companyType,omitempty"`
				CompanyName   string `json:"companyName,omitempty"`
				Office        string `json:"office,omitempty"`
				RequesterType string `json:"requesterType,omitempty"`
			} `json:"client,omitempty"`
			Request struct {
				TargetDate string `json:"targetDate,omitempty"`
				OrderType  string `json:"orderType,omitempty"`
			} `json:"request,omitempty"`
		} `json:"general,omitempty"`
		Vehicle struct {
			VehicleForm struct {
				Color        string `json:"color,omitempty"`
				Vin          string `json:"vin,omitempty"`
				Transmission string `json:"transmission,omitempty"`
				Year         string `json:"year,omitempty"`
				Make         string `json:"make,omitempty"`
				Model        string `json:"model,omitempty"`
			} `json:"vehicleForm,omitempty"`
		} `json:"vehicle,omitempty"`
		Location struct {
			PickupInformation struct {
				City          string `json:"city,omitempty"`
				State         string `json:"state,omitempty"`
				Zip           string `json:"zip,omitempty"`
				Link          string `json:"link,omitempty"`
				Time          string `json:"time,omitempty"`
				PlaceType     string `json:"placeType,omitempty"`
				PlaceName     string `json:"placeName,omitempty"`
				StreetAddress string `json:"streetAddress,omitempty"`
			} `json:"pickupInformation,omitempty"`
			PickupPointOfContact struct {
				FullName           string `json:"fullName,omitempty"`
				Phone              string `json:"phone,omitempty"`
				PickupInstructions string `json:"pickupInstructions,omitempty"`
			} `json:"pickupPointOfContact,omitempty"`
			DeliveryInformation struct {
				PlaceName     string `json:"placeName,omitempty"`
				StreetAddress string `json:"streetAddress,omitempty"`
				City          string `json:"city,omitempty"`
				State         string `json:"state,omitempty"`
				Zip           string `json:"zip,omitempty"`
				Link          string `json:"link,omitempty"`
				Time          string `json:"time,omitempty"`
				PlaceType     string `json:"placeType,omitempty"`
			} `json:"deliveryInformation,omitempty"`
			DeliveryPointOfContact struct {
				FullName             string `json:"fullName,omitempty"`
				Phone                string `json:"phone,omitempty"`
				DeliveryInstructions string `json:"deliveryInstructions,omitempty"`
			} `json:"deliveryPointOfContact,omitempty"`
		} `json:"location,omitempty"`
	} `json:"initialForm,omitempty"`
	General struct {
		ErrorMessages struct {
			Validations struct {
				NotEmpty string `json:"notEmpty,omitempty"`
			} `json:"validations,omitempty"`
			NoEmptyFields string `json:"noEmptyFields,omitempty"`
			Backend       string `json:"backend,omitempty"`
		} `json:"errorMessages,omitempty"`
		FooterButtons []struct {
			Label        string `json:"label,omitempty"`
			Icon         string `json:"icon,omitempty"`
			IconPosition string `json:"iconPosition,omitempty"`
			Action       struct {
				Type    string `json:"type,omitempty"`
				Payload string `json:"payload,omitempty"`
			} `json:"action,omitempty"`
			Navigation bool `json:"navigation,omitempty"`
			Primary    bool `json:"primary,omitempty"`
		} `json:"footerButtons,omitempty"`
		Title    string `json:"title,omitempty"`
		Name     string `json:"name,omitempty"`
		Sections []struct {
			Title  string `json:"title,omitempty"`
			Name   string `json:"name,omitempty"`
			Fields []struct {
				InputType   string `json:"inputType,omitempty"`
				Validations []struct {
					MessageKey string `json:"messageKey,omitempty"`
				} `json:"validations,omitempty"`
				Options []struct {
					Value string `json:"value,omitempty"`
					Label string `json:"label,omitempty"`
				} `json:"options,omitempty"`
				Order       int    `json:"order,omitempty"`
				Placeholder string `json:"placeholder,omitempty"`
				Label       string `json:"label,omitempty"`
				Name        string `json:"name,omitempty"`
				InputMode   string `json:"inputMode,omitempty"`
			} `json:"fields,omitempty"`
		} `json:"sections,omitempty"`
		Dirty bool `json:"dirty,omitempty"`
	} `json:"general,omitempty"`
	Vehicle struct {
		Dirty         bool `json:"dirty,omitempty"`
		ErrorMessages struct {
			NoEmptyFields   string `json:"noEmptyFields,omitempty"`
			NoInvalidFields string `json:"noInvalidFields,omitempty"`
			Backend         string `json:"backend,omitempty"`
			Validations     struct {
				CheckVIN    string `json:"checkVIN,omitempty"`
				NotEmpty    string `json:"notEmpty,omitempty"`
				GreaterThan string `json:"greaterThan,omitempty"`
				LessThan    string `json:"lessThan,omitempty"`
			} `json:"validations,omitempty"`
		} `json:"errorMessages,omitempty"`
		Title         string `json:"title,omitempty"`
		Name          string `json:"name,omitempty"`
		FooterButtons []struct {
			Primary      bool   `json:"primary,omitempty"`
			Label        string `json:"label,omitempty"`
			Icon         string `json:"icon,omitempty"`
			IconPosition string `json:"iconPosition,omitempty"`
			Action       struct {
				Type string `json:"type,omitempty"`
			} `json:"action,omitempty"`
			Navigation bool `json:"navigation,omitempty"`
		} `json:"footerButtons,omitempty"`
		Sections []struct {
			Title  string `json:"title,omitempty"`
			Name   string `json:"name,omitempty"`
			Fields []struct {
				Type        string `json:"type,omitempty"`
				Validations []struct {
					MessageKey string `json:"messageKey,omitempty"`
				} `json:"validations,omitempty"`
				Order        int    `json:"order,omitempty"`
				Placeholder  string `json:"placeholder,omitempty"`
				Label        string `json:"label,omitempty"`
				InputMode    string `json:"inputMode,omitempty"`
				InputType    string `json:"inputType,omitempty"`
				Name         string `json:"name,omitempty"`
				Autocomplete bool   `json:"autocomplete,omitempty"`
				Icon         string `json:"icon,omitempty"`
			} `json:"fields,omitempty"`
		} `json:"sections,omitempty"`
	} `json:"vehicle,omitempty"`
	Location struct {
		Dirty         bool `json:"dirty,omitempty"`
		ErrorMessages struct {
			NoEmptyFields string `json:"noEmptyFields,omitempty"`
			Backend       string `json:"backend,omitempty"`
			Validations   struct {
				NotEmpty string `json:"notEmpty,omitempty"`
			} `json:"validations,omitempty"`
		} `json:"errorMessages,omitempty"`
		Title    string `json:"title,omitempty"`
		Name     string `json:"name,omitempty"`
		Sections []struct {
			Title  string `json:"title,omitempty"`
			Name   string `json:"name,omitempty"`
			Fields []struct {
				Label       string `json:"label,omitempty"`
				Name        string `json:"name,omitempty"`
				Order       int    `json:"order,omitempty"`
				Placeholder string `json:"placeholder,omitempty"`
				Icon        string `json:"icon,omitempty"`
				InputMode   string `json:"inputMode,omitempty"`
				InputType   string `json:"inputType,omitempty"`
				Validations []struct {
					MessageKey string `json:"messageKey,omitempty"`
				} `json:"validations,omitempty"`
				Options []struct {
					Value string `json:"value,omitempty"`
					Label string `json:"label,omitempty"`
				} `json:"options,omitempty"`
			} `json:"fields,omitempty"`
		} `json:"sections,omitempty"`
		FooterButtons []struct {
			Label        string `json:"label,omitempty"`
			Icon         string `json:"icon,omitempty"`
			IconPosition string `json:"iconPosition,omitempty"`
			Action       struct {
				Type string `json:"type,omitempty"`
			} `json:"action,omitempty"`
			Navigation bool `json:"navigation,omitempty"`
			Primary    bool `json:"primary,omitempty"`
		} `json:"footerButtons,omitempty"`
	} `json:"location,omitempty"`
	Comments struct {
		Dirty         bool `json:"dirty,omitempty"`
		ErrorMessages struct {
			Backend     string `json:"backend,omitempty"`
			Validations struct {
			} `json:"validations,omitempty"`
		} `json:"errorMessages,omitempty"`
		Title    string `json:"title,omitempty"`
		Sections []struct {
			Title  string `json:"title,omitempty"`
			Name   string `json:"name,omitempty"`
			Fields []struct {
				InputMode   string   `json:"inputMode,omitempty"`
				Validations []string `json:"validations,omitempty"`
				InputType   string   `json:"inputType,omitempty"`
				Order       int      `json:"order,omitempty"`
				Placeholder string   `json:"placeholder,omitempty"`
				Label       string   `json:"label,omitempty"`
				Name        string   `json:"name,omitempty"`
				Icon        string   `json:"icon,omitempty"`
				Type        string   `json:"type,omitempty"`
			} `json:"fields,omitempty"`
		} `json:"sections,omitempty"`
		FooterButtons []struct {
			Icon         string `json:"icon,omitempty"`
			IconPosition string `json:"iconPosition,omitempty"`
			Action       struct {
				Type string `json:"type,omitempty"`
			} `json:"action,omitempty"`
			Navigation bool   `json:"navigation,omitempty"`
			Primary    bool   `json:"primary,omitempty"`
			Label      string `json:"label,omitempty"`
		} `json:"footerButtons,omitempty"`
	} `json:"comments,omitempty"`
	Modals struct {
		ConfirmationModal struct {
			Name     string `json:"name,omitempty"`
			Subtitle string `json:"subtitle,omitempty"`
			Length   int    `json:"length,omitempty"`
			Buttons  []struct {
				Primary bool   `json:"primary,omitempty"`
				IsText  bool   `json:"isText,omitempty"`
				Label   string `json:"label,omitempty"`
				Action  struct {
					Type string `json:"type,omitempty"`
				} `json:"action,omitempty"`
			} `json:"buttons,omitempty"`
		} `json:"confirmationModal,omitempty"`
	} `json:"modals,omitempty"`
	Steps []struct {
		Title string `json:"title,omitempty"`
		Name  string `json:"name,omitempty"`
		Icon  string `json:"icon,omitempty"`
	} `json:"steps,omitempty"`
}
